### ISSUE TITLE
Funktioniert RSCE mit terminal42/contao-fineuploader?

### ISSUE THREAD

**Issue by cyberlussi** [madeyourday/contao-rocksolid-custom-elements#54]
Hi,
ich habe versucht, eine Galerie in RSCE zu erstellen. Dazu wollte ich den terminal42/contao-fineuploader
verwenden, um direkt upload und Bilderauswahl zu verbinden (ohne den Umweg über die CTO-Dateiverwaltung). Das Feld wird angezeigt, upload ins Zielverzeichnis funktioniert (nach Speichern des Inhaltelements). Soweit gut, allerdings speichert RSCE nichts. Entspechend werden auch keine bereits hochgeladen Bilder angezeigt, wenn ich den Eintrag nachträglich bearbeite. 

Funktioniert RSCE mit terminal42/contao-fineuploader?

```
<?php
// rsce_my_element_config.php
return array(
    'label' => array('Mein Element', 'Meine Beschreibung...'),
    'types' => array('content', 'module'),
    'contentCategory' => 'texts',
    'moduleCategory' => 'miscellaneous',
    'standardFields' => array('cssID'),
    'wrapper' => array(
        'type' => 'none',
    ),
    'fields' => array(
        'headline' => array(
            'inputType' => 'standardField',
            'options' => array('h2', 'h3'),
        ),
        'text' => array(
            'label' => array('Text', 'Beschreibung...'),
            'eval' => array('rte' => 'tinyMCE'),
            'inputType' => 'textarea',
        ),
//        'multiSRC' => array(
//            'inputType' => 'standardField',
//        ),
		'gallery' => array(
			'inputType' => 'fineUploader',
			'label' => array('Bilder hochladen', ''),
			'eval' => array(
				'storeFile' => true, // Mandatory to store the file on the server
				'multiple' => true, // Allow multiple files to be uploaded
				'uploadFolder' => 'files/upload', // Upload path (destination folder)
				'uploaderConfig' => 'debug: true', // Custom uploader configuration (JSON)
				'uploaderLimit' => 4, // Maximum files that can be uploaded
				'addToDbafs' => true, // Add files to the database assisted file system
				'extensions' => $GLOBALS['TL_CONFIG']['uploadTypes'], // Allowed extension types
				'maxlength' => 2048000, // Maximum file size
				'doNotOvewrite' => true, // Do not overwrite files in destination folder
				'chunking' => true, // Enable chunking
				'chunkSize' => 2000000, // Chunk size in bytes
				'isGallery' => true,
			),
		),
    ),
);
```

**Comment by ausi** [comment]
Mit Version 1.3.3 sollten keine Kompatibilitätsprobleme mehr auftreten.

**Comment by cyberlussi** [comment]
Merci :) Funktioniert super, wenn ich Bilder hochlade. Wenn ich aber kein Bild hochlade oder alle bisherigen Bilder entferne und speichere, dass kommt folgendes:

```
Warning: unpack(): Type H: not enough input, need 4, have 0 in system/modules/core/library/Contao/String.php on line 557

#0 [internal function]: __error(2, 'unpack(): Type ...', '/Users/...', 557, Array)
#1 system/modules/core/library/Contao/String.php(557): unpack('H8time_low/H4ti...', '')
#2 [internal function]: Contao\String::binToUuid('')
#3 composer/vendor/madeyourday/contao-rocksolid-custom-elements/src/MadeYourDay/Contao/CustomElements.php(299): array_map('String::binToUu...', Array)
#4 system/modules/core/drivers/DC_Table.php(2925): MadeYourDay\Contao\CustomElements->saveCallback('a:1:{i:0;s:0:""...', Object(Contao\DC_Table))
#5 system/modules/core/classes/DataContainer.php(319): Contao\DC_Table->save('a:1:{i:0;s:0:""...')
#6 system/modules/core/drivers/DC_Table.php(1879): Contao\DataContainer->row('{type_legend},t...')
#7 system/modules/core/classes/Backend.php(425): Contao\DC_Table->edit()
#8 contao/main.php(137): Contao\Backend->getBackendModule('article')
#9 contao/main.php(288): Main->run()
#10 {main}


Warning: implode(): Invalid arguments passed in system/modules/core/library/Contao/String.php on line 557

#0 [internal function]: __error(2, 'implode(): Inva...', '/Users/...', 557, Array)
#1 system/modules/core/library/Contao/String.php(557): implode('-', false)
#2 [internal function]: Contao\String::binToUuid('')
#3 composer/vendor/madeyourday/contao-rocksolid-custom-elements/src/MadeYourDay/Contao/CustomElements.php(299): array_map('String::binToUu...', Array)
#4 system/modules/core/drivers/DC_Table.php(2925): MadeYourDay\Contao\CustomElements->saveCallback('a:1:{i:0;s:0:""...', Object(Contao\DC_Table))
#5 system/modules/core/classes/DataContainer.php(319): Contao\DC_Table->save('a:1:{i:0;s:0:""...')
#6 system/modules/core/drivers/DC_Table.php(1879): Contao\DataContainer->row('{type_legend},t...')
#7 system/modules/core/classes/Backend.php(425): Contao\DC_Table->edit()
#8 contao/main.php(137): Contao\Backend->getBackendModule('article')
#9 contao/main.php(288): Main->run()
#10 {main}
```

**Comment by ausi** [comment]
Die Warnung sollte mit Version 1.3.4 auch verschwunden sein.

**Comment by cyberlussi** [comment]
terminal42/contao-fineuploader arbeitet nun perfekt mit der 1.3.4. Danke!
